import dotenv from 'dotenv-safe';

dotenv.config();

const {
  TWITTER_DEV_CONSUMER_KEY,
  TWITTER_DEV_CONSUMER_SECRET,
  TWITTER_DEV_ACCESS_TOKEN_KEY,
  TWITTER_DEV_ACCESS_TOKEN_SECRET,
  MAP_REQUEST_DEV_API_KEY,
} = process.env;
export default {
  TWITTER_CONSUMER_KEY: TWITTER_DEV_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET: TWITTER_DEV_CONSUMER_SECRET,
  TWITTER_ACCESS_TOKEN_KEY: TWITTER_DEV_ACCESS_TOKEN_KEY,
  TWITTER_ACCESS_TOKEN_SECRET: TWITTER_DEV_ACCESS_TOKEN_SECRET,
  MAP_REQUEST_API_KEY: MAP_REQUEST_DEV_API_KEY,
};
