import dotenv from 'dotenv-safe';

dotenv.config();

const {
  TWITTER_PROD_CONSUMER_KEY,
  TWITTER_PROD_CONSUMER_SECRET,
  TWITTER_PROD_ACCESS_TOKEN_KEY,
  TWITTER_PROD_ACCESS_TOKEN_SECRET,
  MAP_REQUEST_PROD_API_KEY,
  NEW_API_PROD_KEY,
} = process.env;
export default {
  TWITTER_CONSUMER_KEY: TWITTER_PROD_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET: TWITTER_PROD_CONSUMER_SECRET,
  TWITTER_ACCESS_TOKEN_KEY: TWITTER_PROD_ACCESS_TOKEN_KEY,
  TWITTER_ACCESS_TOKEN_SECRET: TWITTER_PROD_ACCESS_TOKEN_SECRET,
  MAP_REQUEST_API_KEY: MAP_REQUEST_PROD_API_KEY,
  NEW_API_KEY: NEW_API_PROD_KEY,
};
