import dotenv from 'dotenv-safe';

dotenv.config();

const {
  TWITTER_TEST_CONSUMER_KEY,
  TWITTER_TEST_CONSUMER_SECRET,
  TWITTER_TEST_ACCESS_TOKEN_KEY,
  TWITTER_TEST_ACCESS_TOKEN_SECRET,
  MAP_REQUEST_TEST_API_KEY,
  NEW_API_TEST_KEY,
} = process.env;
export default {
  TWITTER_CONSUMER_KEY: TWITTER_TEST_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET: TWITTER_TEST_CONSUMER_SECRET,
  TWITTER_ACCESS_TOKEN_KEY: TWITTER_TEST_ACCESS_TOKEN_KEY,
  TWITTER_ACCESS_TOKEN_SECRET: TWITTER_TEST_ACCESS_TOKEN_SECRET,
  MAP_REQUEST_API_KEY: MAP_REQUEST_TEST_API_KEY,
  NEW_API_KEY: NEW_API_TEST_KEY,
};
